//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicCompetitionBP2
{
    using System;
    
    public partial class ADDRESS
    {
        public string HOME_NUMBER { get; set; }
        public string CITY { get; set; }
        public string STREET { get; set; }
    }
}
