//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicCompetitionBP2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competiting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Competiting()
        {
            this.MusicPerformance = new HashSet<MusicPerformance>();
        }
    
        public long CompetitorJMBG_SIN { get; set; }
        public int OrganizePublishingHouseID_PH { get; set; }
        public int OrganizeCompetitionID_COMP { get; set; }
    
        public virtual Competitor Competitor { get; set; }
        public virtual Organize Organize { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusicPerformance> MusicPerformance { get; set; }
    }
}
