//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicCompetitionBP2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evaluate
    {
        public short MARK { get; set; }
        public string COMMENT { get; set; }
        public long IsExpertJuryMemberJMBG_SIN { get; set; }
        public int IsExpertGenreID_GENRE { get; set; }
        public int MusicPerformanceID_PERF { get; set; }
    
        public virtual IsExpert IsExpert { get; set; }
        public virtual MusicPerformance MusicPerformance { get; set; }
    }
}
