//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicCompetitionBP2
{
    using System;
    using System.Collections.Generic;
    
    public partial class HiredFor
    {
        public long JuryMemberJMBG_SIN { get; set; }
        public int CompetitionID_COMP { get; set; }
    
        public virtual JuryMember JuryMember { get; set; }
        public virtual Competition Competition { get; set; }
    }
}
