//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicCompetitionBP2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserve
    {
        public System.DateTime DATE_RES { get; set; }
        public System.TimeSpan START_TIME { get; set; }
        public System.TimeSpan END_TIME { get; set; }
        public int OrganizePublishingHouseID_PH { get; set; }
        public int OrganizeCompetitionID_COMP { get; set; }
        public int PerformanceHallID_HALL { get; set; }
    
        public virtual Organize Organize { get; set; }
        public virtual PerformanceHall PerformanceHall { get; set; }
    }
}
